# Generated by Django 5.0.2 on 2025-03-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Инициализация забега'), ('in_progress', 'Забег в процессе'), ('finished', 'Забег окончен')], default='init', max_length=30),
        ),
    ]
