# Generated by Django 5.0.2 on 2025-04-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
