# Generated by Django 5.0.2 on 2025-04-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_run_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
