# Generated by Django 5.0.2 on 2025-04-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
